### ISSUE TITLE
Xcode 11 code coverage reports are not exported in ouput directory

### ISSUE THREAD

**Issue by FabienLydoire** [fastlane-community/xcov#157]
Hello fastlane community,

Although Xcode11 xcresult support has been added in PR #155, this does not restore the code coverage features we had using Xcode 10, especially when using multiple schemes.

With Xcode 10, passing `code_coverage:true` to `Scan` resulted in `action.xccovreport` and `action.xccovarchive` files in the test results bundle.

With Xcode 11, the code coverage report files are not created in the test bundle anymore.

`Xcov` relies on `XCResult` to parse the test results bundle and create an `action.xccovreport` file used to create a fancy HTML/Markdown/JSON report.
The `action.xccovreport` is created in a temporary folder and not exported in the output directory -> I think it's a bug 🐛 : it should be exported.

Moreover, there is no `action.xccovarchive` extracted from the test results bundle data.

When using multiple schemes, we want a code coverage report file to pass to Danger to get an overview of the coverage across all schemes in our Pull Requests.
With Xcode 10, we merged the code coverage reports using `xcrun xccov merge` but this command requires **both** the `action.xccovreport` and the `action.xccovarchive`.
There is no way to extract an `action.xccovarchive` from Xcode 11 test results bundle so we can not merge tests reports any more.

Can someone advise on how to get coverage reports in a PR in Bibucket when running multiple schemes in the same CI job ? Thanks !

**Comment by joshdholtz** [comment]
@FabienLydoire Hey, thanks for the detailed issue 😊 I _thhiinnnkkkkk_ I found out how to get an `xccovarchive` but I'm honestly not sure what the contents of the file is supposed to look like 🙃 Do you have an example of one and/or a link to documentation what its supposed to contain?

**Comment by FabienLydoire** [comment]
Hi @joshdholtz, I would be glad to test your branch. 
Will you output the 2 files of coverage report in the output folder ?

**Comment by joshdholtz** [comment]
@FabienLydoire You would like them in the output folder or in the same directory as the `xcresult`? I would probably personally prefer the output folder if that works for you 😊

**Comment by joshdholtz** [comment]
@FabienLydoire Here it is! ☝️

**Comment by FabienLydoire** [comment]
Thanks @joshdholtz 
I did launch `scan` with `code_coverage:true`.
I would like to use `xcov` to get the `.xccovarchive` and `.xccovreport` from the `.xcresult` bundle, so I launched `bundle exec xcov -f  <path to .xcresult bundle` and I got an error
```bundler: failed to load command: xcov (/Library/Ruby/Gems/2.6.0/bin/xcov)
NameError: [!] undefined local variable or method `path' for #<Xcov::Manager:0x00007f827888b420>
  /Users/fabienlydoire/.bundle/ruby/2.6.0/xcov-ad261af3e945/lib/xcov/manager.rb:62:in `parse_xccoverage'
  /Users/fabienlydoire/.bundle/ruby/2.6.0/xcov-ad261af3e945/lib/xcov/manager.rb:32:in `run'
  /Users/fabienlydoire/.bundle/ruby/2.6.0/xcov-ad261af3e945/lib/xcov/commands_generator.rb:41:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.133.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Users/fabienlydoire/.bundle/ruby/2.6.0/xcov-ad261af3e945/lib/xcov/commands_generator.rb:46:in `run'
  /Users/fabienlydoire/.bundle/ruby/2.6.0/xcov-ad261af3e945/lib/xcov/commands_generator.rb:15:in `start'
  /Users/fabienlydoire/.bundle/ruby/2.6.0/xcov-ad261af3e945/bin/xcov:6:in `<top (required)>'
  /Library/Ruby/Gems/2.6.0/bin/xcov:23:in `load'
  /Library/Ruby/Gems/2.6.0/bin/xcov:23:in `<top (required)>'
```
1. Am I using `xcov` as I am supposed to ?
2. How to I get the `.xccovarchive` and `.xccovreport` from the `.xcresult` bundle ?
3. Do I have to add `xcov` in the fastfile lane after the `scan` command ?

**Comment by narlei** [comment]
This error here:
````
+----------------------------+---------------------------------------------------------------------------------------------+
[11:16:35]: Error creating your coverage report - see the log above

+------+-----------------------------+-------------+
|                 fastlane summary                 |
+------+-----------------------------+-------------+
| Step | Action                      | Time (in s) |
+------+-----------------------------+-------------+
| 1    | default_platform            | 0           |
| 2    | run_tests                   | 620         |
| 3    | Switch to ios coverage lane | 0           |
| 💥   | xcov                        | 6           |
| 5    | get_version_number          | 0           |
| 6    | get_build_number            | 0           |
| 7    | get_version_number          | 0           |
| 8    | get_build_number            | 0           |
| 9    | google_chat                 | 1           |
+------+-----------------------------+-------------+

[11:16:35]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
Traceback (most recent call last):
	40: from /Users/narlei/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `<main>'
	39: from /Users/narlei/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `eval'
	38: from /Users/narlei/.rvm/gems/ruby-2.6.0/bin/fastlane:23:in `<main>'
	37: from /Users/narlei/.rvm/gems/ruby-2.6.0/bin/fastlane:23:in `load'
	36: from /Users/narlei/.rvm/gems/ruby-2.6.0/gems/fastlane-2.133.0/bin/fastlane:23:in `<top (required)>'
	35: from /Users/narlei/.rvm/gems/ruby-2.6.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	34: from /Users/narlei/.rvm/gems/ruby-2.6.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	33: from /Users/narlei/.rvm/gems/ruby-2.6.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/commands_generator.rb:349:in `run'
	32: from /Users/narlei/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	31: from /Users/narlei/.rvm/gems/ruby-2.6.0/gems/fastlane-2.133.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	30: from /Users/narlei/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	29: from /Users/narlei/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	28: from /Users/narlei/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	27: from /Users/narlei/.rvm/gems/ruby-2.6.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	26: from /Users/narlei/.rvm/gems/ruby-2.6.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	25: from /Users/narlei/.rvm/gems/ruby-2.6.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	24: from /Users/narlei/.rvm/gems/ruby-2.6.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	23: from /Users/narlei/.rvm/gems/ruby-2.6.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	22: from /Users/narlei/.rvm/gems/ruby-2.6.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	21: from /Users/narlei/.rvm/gems/ruby-2.6.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	20: from Fastfile:276:in `block (2 levels) in parsing_binding'
	19: from /Users/narlei/.rvm/gems/ruby-2.6.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	18: from /Users/narlei/.rvm/gems/ruby-2.6.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
	17: from /Users/narlei/.rvm/gems/ruby-2.6.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
	16: from /Users/narlei/.rvm/gems/ruby-2.6.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	15: from Fastfile:260:in `block (2 levels) in parsing_binding'
	14: from /Users/narlei/.rvm/gems/ruby-2.6.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	13: from /Users/narlei/.rvm/gems/ruby-2.6.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	12: from /Users/narlei/.rvm/gems/ruby-2.6.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	11: from /Users/narlei/.rvm/gems/ruby-2.6.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	10: from /Users/narlei/.rvm/gems/ruby-2.6.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
	 9: from /Users/narlei/.rvm/gems/ruby-2.6.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	 8: from /Users/narlei/.rvm/gems/ruby-2.6.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
	 7: from /Users/narlei/.rvm/gems/ruby-2.6.0/gems/fastlane-2.133.0/fastlane/lib/fastlane/actions/xcov.rb:8:in `run'
	 6: from /Users/narlei/.rvm/gems/ruby-2.6.0/bundler/gems/xcov-53a2c38c59e1/lib/xcov/manager.rb:32:in `run'
	 5: from /Users/narlei/.rvm/gems/ruby-2.6.0/bundler/gems/xcov-53a2c38c59e1/lib/xcov/manager.rb:65:in `parse_xccoverage'
	 4: from /Users/narlei/.rvm/gems/ruby-2.6.0/bundler/gems/xcov-53a2c38c59e1/lib/xcov-core.rb:24:in `parse'
	 3: from /Users/narlei/.rvm/gems/ruby-2.6.0/bundler/gems/xcov-53a2c38c59e1/lib/xcov-core.rb:30:in `execute_command'
	 2: from /Users/narlei/.rvm/gems/ruby-2.6.0/gems/fastlane-2.133.0/fastlane_core/lib/fastlane_core/command_executor.rb:89:in `execute'
	 1: from /Users/narlei/.rvm/gems/ruby-2.6.0/bundler/gems/xcov-53a2c38c59e1/lib/xcov-core.rb:38:in `block in execute_command'
/Users/narlei/.rvm/gems/ruby-2.6.0/bundler/gems/xcov-53a2c38c59e1/lib/xcov/error_handler.rb:20:in `handle_error': [!] Error creating your coverage report - see the log above (RuntimeError)
````

**Comment by FabienLydoire** [comment]
👋🏻 @joshdholtz !
I understand it's a low priority item wrt. the rest of fastlane code, but is there a chance you can fix this PR ? I'm far from being a ruby expert myself.

**Comment by FabienLydoire** [comment]
👋🏻 @joshdholtz !
I understand it's a low priority item wrt. the rest of fastlane code, but is there a chance you can fix this PR ? I'm far from being a ruby expert myself.

**Comment by giovas17** [comment]
I have exactly the same issue, Do you have any update in this??

**Comment by FabienLydoire** [comment]
@cristianbanarescu The PR is done but it crashes. The PR needs to be fixed and I don't think @joshdholtz has time at the moment.

**Comment by cristianbanarescu** [comment]
Ok, @FabienLydoire ! Thank you for your response !

**Comment by joshdholtz** [comment]
Heyyy! Sorry about that! I will take a look at today to hopefully get it fixed up 💪
