### ISSUE TITLE
"Error occured while exporting xccovreport from xcresult" when using Xcode 11.7

### ISSUE THREAD

**Issue by denysowova** [fastlane-community/xcov#187]
Hello. I'm using xcov locally to test it with our project and plan to use it later in our Bitrise pipeline. It works well with Xcode 12, but when switching the command line tools to Xcode 11.7, the following error is thrown:

```
 Error occured while exporting xccovreport from xcresult '/DerivedData/TestApp-cecebhsfvzltmlebjlxheijkwewa/Logs/Test/Run-TestApp-2020.10.07_17-51-01-+0300.xcresult'
Make sure you have both Xcode 11 selected and pointing to the correct xcresult file
```

Any possible fix on that? Thanks in advance.

**Comment by joshdholtz** [comment]
This looks like a similar issue to https://github.com/fastlane-community/danger-xcov/issues/33

I’ll add this to my queue to look into! Probably won’t be able to get to it myself this week 😔

**Comment by denysowova** [comment]
Thank you, @joshdholtz

**Comment by XiaoxiaYao** [comment]
It's weird. I am using Xcode 12.2. Facing the same issue. Will wait for the fix. Thank you @joshdholtz  in advance.

**Comment by weibel** [comment]
xcov 1.7.5, Xcode 12.2,  Command example: 
>  xcov --html_report false --only_project_targets -s BandLibrary --derived_data_path ./DerivedData -o ./ -f bandlibrary.xcresult

On Xcode 12.2 xcov would complain with
> /Users/jenkins/.rvm/gems/ruby-2.6.5@unit_test/gems/xcov-1.7.5/lib/xcov/manager.rb:225:in `rename': Directory not empty @ rb_file_s_rename - (./action_0.xccovarchive, ./xccovarchive-0.xccovarchive) (Errno::ENOTEMPTY)

In manager.rb I replaced lines 225 and 226 with
```ruby
FileUtils.mv(tmp_archive_paths[i], "#{output_path}/xccovarchive-#{index + i}.xccovarchive", force: true)
FileUtils.mv(item, "#{output_path}/xccovreport-#{index + i}.xccovreport", force: true)
```
Then it would process. However prior to this I had already copied a number of .xcovreports and .xcovarchives into the directory for later processing which xcov now seemed to pick up e.g. both with
> Merging multiple coverage reports with <here follows all previosly stored .xcovereports and .xcovarchives>
and
> Copying .xccovreport to ./apiconnectorslibrary.xccovreport

**Comment by asam139** [comment]
Same problem using 12.4

Traceback (most recent call last):
	39: from /Users/93sauu/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
	38: from /Users/93sauu/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
	37: from /Users/93sauu/.rvm/gems/ruby-2.6.3/bin/fastlane:23:in `<main>'
	36: from /Users/93sauu/.rvm/gems/ruby-2.6.3/bin/fastlane:23:in `load'
	35: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/bin/fastlane:23:in `<top (required)>'
	34: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	33: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	32: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	31: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	30: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	29: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	28: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	27: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	26: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	25: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	24: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	23: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	22: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	21: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	20: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	19: from Fastfile:118:in `block (2 levels) in parsing_binding'
	18: from Fastfile:138:in `check_xcov'
	17: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	16: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	15: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	14: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	13: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	12: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	11: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	10: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/fastlane/lib/fastlane/actions/xcov.rb:8:in `run'
	 9: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/xcov-1.7.5/lib/xcov/manager.rb:32:in `run'
	 8: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/xcov-1.7.5/lib/xcov/manager.rb:84:in `parse_xccoverage'
	 7: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/xcov-1.7.5/lib/xcov/manager.rb:215:in `process_xcresults!'
	 6: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/xcov-1.7.5/lib/xcov/manager.rb:215:in `flat_map'
	 5: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/xcov-1.7.5/lib/xcov/manager.rb:215:in `each'
	 4: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/xcov-1.7.5/lib/xcov/manager.rb:224:in `block in process_xcresults!'
	 3: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/xcov-1.7.5/lib/xcov/manager.rb:224:in `each_with_index'
	 2: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/xcov-1.7.5/lib/xcov/manager.rb:224:in `each'
	 1: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/xcov-1.7.5/lib/xcov/manager.rb:225:in `block (2 levels) in process_xcresults!'
/Users/93sauu/.rvm/gems/ruby-2.6.3/gems/xcov-1.7.5/lib/xcov/manager.rb:225:in `rename': Directory not empty @ rb_file_s_rename - (fastlane/xcov_output/action_0.xccovarchive, fastlane/xcov_output/xccovarchive-0.xccovarchive) (Errno::ENOTEMPTY)
	38: from /Users/93sauu/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
	37: from /Users/93sauu/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
	36: from /Users/93sauu/.rvm/gems/ruby-2.6.3/bin/fastlane:23:in `<main>'
	35: from /Users/93sauu/.rvm/gems/ruby-2.6.3/bin/fastlane:23:in `load'
	34: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/bin/fastlane:23:in `<top (required)>'
	33: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	32: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	31: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	30: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	29: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	28: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	27: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	26: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	25: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	24: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	23: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	22: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	21: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	20: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	19: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	18: from Fastfile:118:in `block (2 levels) in parsing_binding'
	17: from Fastfile:138:in `check_xcov'
	16: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	15: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	14: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	13: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	12: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	11: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	10: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	 9: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/fastlane/lib/fastlane/actions/xcov.rb:8:in `run'
	 8: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/xcov-1.7.5/lib/xcov/manager.rb:32:in `run'
	 7: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/xcov-1.7.5/lib/xcov/manager.rb:84:in `parse_xccoverage'
	 6: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/xcov-1.7.5/lib/xcov/manager.rb:215:in `process_xcresults!'
	 5: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/xcov-1.7.5/lib/xcov/manager.rb:215:in `flat_map'
	 4: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/xcov-1.7.5/lib/xcov/manager.rb:215:in `each'
	 3: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/xcov-1.7.5/lib/xcov/manager.rb:216:in `block in process_xcresults!'
	 2: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/xcov-1.7.5/lib/xcov/manager.rb:232:in `rescue in block in process_xcresults!'
	 1: from /Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Users/93sauu/.rvm/gems/ruby-2.6.3/gems/fastlane-2.176.0/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': [!] Failed to export xccovreport from xcresult' (FastlaneCore::Interface::FastlaneCrash)

**Comment by cameronehrlich** [comment]
Anyone have a workaround for this?

**Comment by HossamYoussof** [comment]
Clear output directory before check 

```
    clear_derived_data(derived_data_path: COVERAGE_OUTPUT_PATH)

    xcov(
      skip_slack: true,
      scheme: LIVE_SCHEME,
      output_directory: COVERAGE_OUTPUT_PATH,
      derived_data_path: DERIVED_DATA_PATH,
      minimum_coverage_percentage: MINIMUM_COVERAGE_PERCENTAGE
    )
```

**Comment by BeibeiLewis** [comment]
> Hello. I'm using xcov locally to test it with our project and plan to use it later in our Bitrise pipeline. It works well with Xcode 12, but when switching the command line tools to Xcode 11.7, the following error is thrown:
> 
> ```
> Error occured while exporting xccovreport from xcresult '/DerivedData/TestApp-cecebhsfvzltmlebjlxheijkwewa/Logs/Test/Run-TestApp-2020.10.07_17-51-01-+0300.xcresult'
> Make sure you have both Xcode 11 selected and pointing to the correct xcresult file
> ```
> 
> Any possible fix on that? Thanks in advance.

Hello, Have you resolved the issue?  i hit the issue too.

**Comment by MagFer** [comment]
Are you using M1/2/3 machines? This could be related to https://github.com/fastlane-community/xcov/issues/222

**Comment by imranMnts** [comment]
any update? it still doesn't work on XCode 15.3 (M1)

someone know how to fix it?

**Comment by michal-niemiec-tech** [comment]
@joshdholtz
Hello, can you give us more informations how is going with this bug?
