### ISSUE TITLE
`PBXProject` attempted to initialize an object with unknown ISA `XCLocalSwiftPackageReference`

### ISSUE THREAD

**Issue by nebsta** [fastlane-community/xcov#221]
We're currently having an issue with version 1.8.1 of xcov whereby we get this error whenever we try to generate the coverage report

```
/Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/object.rb:359:in `rescue in object_with_uuid': [!] `PBXProject` attempted to initialize an object with unknown ISA `XCLocalSwiftPackageReference` from attributes: `{"isa"=>"XCLocalSwiftPackageReference", "relativePath"=>"TrustpilotMacros"}` (RuntimeError)
If this ISA was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/object.rb:349:in `object_with_uuid'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/object.rb:299:in `each'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/object.rb:296:in `each'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project.rb:272:in `new_from_plist'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project.rb:213:in `initialize_from_file'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project.rb:113:in `open'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/xcov-1.8.1/lib/xcov/project_extensions.rb:12:in `targets'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/xcov-1.8.1/lib/xcov/model/report.rb:82:in `filter_targets'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/xcov-1.8.1/lib/xcov/model/report.rb:56:in `map'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/xcov-1.8.1/lib/xcov/manager.rb:111:in `generate_xcov_report'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/xcov-1.8.1/lib/xcov/manager.rb:35:in `run'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/actions/xcov.rb:13:in `run'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:115:in `block (2 levels) in parsing_binding'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.216.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.216.0/bin/fastlane:23:in `<top (required)>'
	from /Users/vagrant/.asdf/installs/ruby/3.2/bin/fastlane:25:in `load'
	from /Users/vagrant/.asdf/installs/ruby/3.2/bin/fastlane:25:in `<main>'
/Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project.rb:268:in `new_from_plist': uninitialized constant Xcodeproj::Project::Object::XCLocalSwiftPackageReference (NameError)
        klass = Object.const_get(attributes['isa'])
                      ^^^^^^^^^^
Did you mean?  Xcodeproj::Project::Object::XCRemoteSwiftPackageReference
               Xcodeproj::Project::XCRemoteSwiftPackageReference
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/object.rb:350:in `object_with_uuid'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/object.rb:300:in `block (2 levels) in configure_with_plist'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/object.rb:299:in `each'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/object.rb:299:in `block in configure_with_plist'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/object.rb:296:in `each'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/object.rb:296:in `configure_with_plist'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project.rb:272:in `new_from_plist'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project.rb:213:in `initialize_from_file'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project.rb:113:in `open'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/xcov-1.8.1/lib/xcov/project_extensions.rb:12:in `targets'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/xcov-1.8.1/lib/xcov/model/report.rb:82:in `filter_targets'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/xcov-1.8.1/lib/xcov/model/report.rb:56:in `map'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/xcov-1.8.1/lib/xcov/manager.rb:111:in `generate_xcov_report'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/xcov-1.8.1/lib/xcov/manager.rb:35:in `run'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/actions/xcov.rb:13:in `run'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:115:in `block (2 levels) in parsing_binding'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.216.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.216.0/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /Users/vagrant/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/fastlane-2.216.0/bin/fastlane:23:in `<top (required)>'
	from /Users/vagrant/.asdf/installs/ruby/3.2/bin/fastlane:25:in `load'
	from /Users/vagrant/.asdf/installs/ruby/3.2/bin/fastlane:25:in `<main>'
[!] `PBXProject` attempted to initialize an object with unknown ISA `XCLocalSwiftPackageReference` from attributes: `{"isa"=>"XCLocalSwiftPackageReference", "relativePath"=>"TrustpilotMacros"}` (RuntimeError)
If this ISA was generated by Xcode please file an issue: https://github.com/CocoaPods/Xcodeproj/issues/new
```

I believe this has to do with the xcodeproj dependency still being on version 1.22.0, as there was a fix in version 1.23.0 for supporting XCLocalSwiftPackageReference object types: https://github.com/CocoaPods/Xcodeproj/releases/tag/1.23.0

**Comment by lalejzapata** [comment]
Upgrading xcodeproj version in Gemfile fixed the issue for me
