### ISSUE TITLE
"Error occured while exporting xccovreport from xcresult" when "xcov_report" folder already exists

### ISSUE THREAD

**Issue by clemens-unterkofler** [fastlane-community/xcov#222]
xcov 1.8.1
XCode 15.0

misleading error message:
`Make sure you have both Xcode 11 selected and pointing to the correct xcresult file`

top of stack trace:
```
~/.gem/ruby/3.2.0/gems/fastlane-2.219.0/fastlane_core/lib/fastlane_core/ui/interface.rb:129:in `crash!': [!] Failed to export xccovreport from xcresult' (FastlaneCore::Interface::FastlaneCrash)
from ~/.gem/ruby/3.2.0/gems/fastlane-2.219.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
```

runs fine again after "rm -rf xcov_report"

**Comment by MagFer** [comment]
I can see the same error when I run the command `bundle exec xcov -w {app}.xcworkspace -s {scheme} -o xcov_output` form an M1 machine. Nevertheless, this issue doesn't happen in my MacBook with Intel i9. 

Is anyone else having issues with running `xcov` in Macs using ARM processors? We do use M2 machines in the CI, and going back to Intel at this point isn't an option.
